objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Signature_Date__c</fullName>
        <inlineHelpText>Date written next to the signature</inlineHelpText>
        <label>Contract Signature Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enddatee__c</fullName>
        <inlineHelpText>The date on which the supply of contracted goods or services end (ex. Last Delivery Contracted Date)</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>startDatee__c</fullName>
        <inlineHelpText>The date on which the supply of contracted goods or services begins (ex. First Delivery Contracted Date)</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity from which this contract was created</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__QuoteId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote from which this contract was created</description>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DeliveryPlan__c.object
<CustomObject>
    <fields>
        <fullName>Grid_Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Delivery Plans</relationshipLabel>
        <relationshipName>Delivery_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleCount__c</fullName>
        <inlineHelpText>Please put a number between 0 and 24</inlineHelpText>
        <label>Schedule Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleFrequency__c</fullName>
        <label>Schedule Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>One time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                    <isActive>false</isActive>
                    <label>Weekly</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grid_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Grid_Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Plan</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Grid_RevenueSchedule__c.object
<CustomObject>
    <fields>
        <fullName>Grid_ActualAmount__c</fullName>
        <label>Actual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grid_Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grid_ContractLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Line</label>
        <referenceTo>vlocity_cmt__ContractLineItem__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_Metric__c</fullName>
        <label>Metric</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>Recurring Monthly</fullName>
                </value>
                <value>
                    <fullName>Recurring Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grid_PlannedAmount__c</fullName>
        <label>Planned Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grid_QuoteLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_Revenue__c</fullName>
        <description>Revenue Master-Detail Relationship</description>
        <label>Revenue</label>
        <referenceTo>Revenue__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Grid_RevenueSchedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grid_StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Version__c</fullName>
        <label>Version</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Revenue Schedule</label>
    <nameField>
        <label>Revenue Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Grid_Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED. Use the standard OpportunityId field.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__QuoteId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED. Use the standard QuoteId field.</description>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductSchedule__c.object
<CustomObject>
    <fields>
        <fullName>Grid_ContractLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Line</label>
        <referenceTo>vlocity_cmt__ContractLineItem__c</referenceTo>
        <relationshipLabel>Product Schedules</relationshipLabel>
        <relationshipName>Product_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_Delivery_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Plan</label>
        <referenceTo>DeliveryPlan__c</referenceTo>
        <relationshipLabel>Product Schedules</relationshipLabel>
        <relationshipName>Product_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_PlannedAmount__c</fullName>
        <label>Planned Amount2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grid_PlannedQuantity__c</fullName>
        <label>Planned Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_QuoteLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Product Schedules</relationshipLabel>
        <relationshipName>Product_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_SalesPric__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grid_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Grid_Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Revenue__c.object
<CustomObject>
    <fields>
        <fullName>Grid_Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship to Quote object</description>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Revenues</relationshipLabel>
        <relationshipName>Revenues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_StartDate__c</fullName>
        <description>Opportunity Start Date</description>
        <formula>Grid_Quote__r.Opportunity.Grid_StartContractDate__c</formula>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Revenue</label>
    <nameField>
        <label>Revenue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Grid_OrderServiceClassTest.cls
@IsTest
private class Grid_OrderServiceClassTest {
    
     @TestSetup
    private static void prepareData() {
        Id pricebookId = Test.getStandardPricebookId(); 
        Account acc = (Account) TestDataFactory.createSObject(
            'Account',
            new Map<String, Object>{
              'Name' => 'TestAccount',
              'CurrencyIsoCode'=> 'EUR'
            },
            true
          );
        Opportunity oppo = (Opportunity) TestDataFactory.createSObject(
            'Opportunity',
            new Map<String, Object>{
               'StageName' => 'Internal Review',
               'Grid_StartContractDate__c' => System.today(),
               'AccountId' => acc.Id,
               'Grid_EndContractDate__c' => Date.newInstance(         
                 System.today().year()+3,
                 System.today().month(),
                 System.today().day()
                 )
              },
            true
          );
          vlocity_cmt__PriceList__c spainPriceList = (vlocity_cmt__PriceList__c) TestDataFactory.createSObject(
            'vlocity_cmt__PriceList__c',
            new Map<String, Object>{
              'CurrencyIsoCode' => 'EUR',
              'vlocity_cmt__Code__c' => 'testcode'
            },
            true
          );
          Quote quote = (Quote) TestDataFactory.createSObject(
            'Quote',
            new Map<String, Object>{
              'OpportunityId' => oppo.Id,
              'Pricebook2Id' => pricebookId
            },
            true
          );
          Product2 prod = (Product2) TestDataFactory.createSObject(
            'Product2',
            new Map<String, Object>{
              'Name' => 'Testing Product',
              'Grid_Category__c' => 'Hardware',
              'Grid_IsChild__c' => true   
            },
            true
          );
          Product2 prod2 = (Product2) TestDataFactory.createSObject(
            'Product2',
            new Map<String, Object>{
              'Name' => 'Testing Product22',
              'Grid_Category__c' => 'Software',
              'Grid_IsChild__c' => true
            },
            true
          );
          PricebookEntry priceBook = (PricebookEntry) TestDataFactory.createSObject(
            'PricebookEntry',
            new Map<String, Object>{
              'Pricebook2Id' => pricebookId,
              'Product2Id' => prod.Id,
              'Product2' => prod, 
              'IsActive' => true,
              'UnitPrice' => 0
            },
            true
          );
          PricebookEntry priceBook2 = (PricebookEntry) TestDataFactory.createSObject(
            'PricebookEntry',
            new Map<String, Object>{
              'Pricebook2Id' => pricebookId,
              'Product2Id' => prod2.Id,
              'Product2' => prod2, 
              'IsActive' => true,
              'UnitPrice' => 0
            },
            true
          );
    
          Quotelineitem qli = (Quotelineitem) TestDataFactory.createSObject(
            'Quotelineitem',
            new Map<String, Object>{
              'QuoteId' => quote.Id,
              'Quantity' => 3,
              'Product2' => prod,
              'PricebookEntryId' => priceBook.Id
            },
            true
          );
          Quotelineitem qli2 = (Quotelineitem) TestDataFactory.createSObject(
            'Quotelineitem',
            new Map<String, Object>{
              'QuoteId' => quote.Id,
              'Quantity' => 77,
              'Product2' => prod2,
              'PricebookEntryId' => priceBook.Id
            },
            true
          );
        // Create a mock Contract record
        Contract contract = (Contract) TestDataFactory.createSObject(
            'Contract',
            new Map<String, Object>{
                'Status' => 'Draft',
                'vlocity_cmt__OpportunityId__c' => oppo.Id,
                'vlocity_cmt__QuoteId__c' => quote.Id,
                'AccountId' => acc.Id,
                'Contract_Signature_Date__c' => System.today(),
                'startDatee__c' => System.today(),
                'Enddatee__c' => System.today() + 5
                },
                true
        );
        vlocity_cmt__ContractLineItem__c contractLine = (vlocity_cmt__ContractLineItem__c) TestDataFactory.createSObject(
            'vlocity_cmt__ContractLineItem__c',
            new Map<String, Object>{
                'vlocity_cmt__ContractId__c' => contract.Id,
                'vlocity_cmt__Product2Id__c' => prod2.id
            },
            true
        );
        vlocity_cmt__ContractLineItem__c contractLine2 = (vlocity_cmt__ContractLineItem__c) TestDataFactory.createSObject(
            'vlocity_cmt__ContractLineItem__c',
            new Map<String, Object>{
                'vlocity_cmt__ContractId__c' => contract.Id,
                'vlocity_cmt__Product2Id__c' => prod.id
            },
            true
        );
        Revenue__c revenue = (Revenue__c) TestDataFactory.createSObject(
            'Revenue__c',
            new Map<String, Object>{
                'Grid_Quote__c' => quote.Id,
                'Grid_Version__c' => 1
            },
        true
        );
		DeliveryPlan__c deliveryPlan = (DeliveryPlan__c) TestDataFactory.createSObject(
            'DeliveryPlan__c',
            new Map<String, Object>{
              'Grid_Quote__c' => quote.Id,
              'Grid_StartDate__c' => System.today(),
              'Grid_ScheduleCount__c' => 3,
              'Grid_ScheduleFrequency__c' => 'Yearly'
            },
            true
          );
          ProductSchedule__c prodSched1 = (ProductSchedule__c) TestDataFactory.createSObject(
            'ProductSchedule__c',
            new Map<String, Object>{
              'Grid_QuoteLineItem__c' => qli.Id,
              'Name' => DateTime.newInstance(         
                System.today().year(),
                System.today().month(),
                System.today().day()
                ).format('YYYY'),
              'Grid_Version__c' => 1,
              'Grid_Delivery_Plan__c' => deliveryPlan.Id,
              'Grid_SalesPric__c' => 100,
              'Grid_PlannedQuantity__c' => 2
            },
            true
          );        
        // Create a test revenue schedule record with some fields using the TestDataFactory class
        Grid_RevenueSchedule__c testRS = (Grid_RevenueSchedule__c) TestDataFactory.createSObject(
            'Grid_RevenueSchedule__c',
            new Map<String, Object>{ 
                'Grid_Metric__c' => 'One Time',
                'Grid_QuoteLineItem__c' => qli.Id,
                'Grid_PlannedAmount__c' => 100,
                'Grid_ActualAmount__c' => 90,
                'Grid_Revenue__c' => revenue.Id, 
                'Grid_Version__c' => 1,
                'Grid_ContractLine__c' => contractLine.Id
            },
            true
        );

    }
    
     @IsTest
    static void cloneRevenueTest() {
        Set<Id> contractsSet = new Set<Id>();
        contractsSet.add([Select Id From Contract limit 1].Id);
        Test.startTest();
        Grid_OrderServiceClass.cloneRevenue(contractsSet);
        Test.stopTest();
        List<Revenue__c> revenueList = [ SELECT Id, Grid_Quote__c  FROM Revenue__c];
        Assert.areEqual(2,revenueList.size(),'Revenue not cloned correctly');
    }

    @IsTest
    static void cloneRevenueSchedulesTest() {
        Set<Id> contractsSet = new Set<Id>();
        contractsSet.add([Select Id From Contract limit 1].Id);
        Test.startTest();
        Grid_OrderServiceClass.cloneRevenue(contractsSet);   
        Grid_OrderServiceClass.cloneRevenueSchedules(contractsSet);
        Assert.areEqual(2, [ SELECT Id  FROM Grid_RevenueSchedule__c].size());
        Test.stopTest();
    }

    @IsTest
    static void updateRevenueSchedulesActualTest() {
        Set<Id> contractsSet = new Set<Id>();
        contractsSet.add([Select Id From Contract limit 1].Id);
        Order order = TestDataFactory.createOrder([Select Id From Account Limit 1].Id,[Select Id From Contract limit 1].Id);         
        List<Order> ordersInvoiced = new List<Order>{ order };
        Order.Status = 'Delivered';
        Order.Grid_Delivery_Date__c = system.today();
        update Order; 
        Test.startTest();
        Grid_OrderServiceClass.cloneRevenue(contractsSet);
        Grid_OrderServiceClass.updateRevenueSchedulesActual(ordersInvoiced, false);
        Test.stopTest();
    }
     @IsTest
    static void updateRelatedProductScheduelleTest() {
        Set<Id> contractsSet = new Set<Id>();
        contractsSet.add([Select Id From Contract limit 1].Id);
        Order order = TestDataFactory.createOrder([Select Id From Account Limit 1].Id,[Select Id From Contract limit 1].Id);         
        List<Order> ordersInvoiced = new List<Order>{ order };
        Order.Status = 'Delivered';
        Order.Grid_Delivery_Date__c = system.today();
        update Order; 
        Test.startTest();
        Grid_OrderServiceClass.cloneRevenue(contractsSet);
        Grid_OrderServiceClass.updateRelatedProductScheduelle(ordersInvoiced);
        Test.stopTest();
    }

     @IsTest
    static void UpdateQuantityInContractLineTest() {
        
        Order order = TestDataFactory.createOrder([Select Id From Account Limit 1].Id,[Select Id From Contract limit 1].Id);  
        Order.Status = 'Delivered';
        update Order;
        OrderItem om = TestDataFactory.createOrderItems(order.Id);
        List<Order> ordersInvoiced = new List<Order>{ order };
        Test.startTest();
        Grid_OrderServiceClass.updateQuantityInContractLine(ordersInvoiced);
        Test.stopTest();
    }
     @IsTest
    static void updateFlrOrchestrationStatusTest() {
        Order order = TestDataFactory.createOrder([Select Id From Account Limit 1].Id,[Select Id From Contract limit 1].Id);
        Order.Status = 'SAP KO';
        update Order;
        OrderItem om = TestDataFactory.createOrderItems(order.Id);
        vlocity_cmt__OrchestrationItem__c orchI = TestDataFactory.createOrchestrationItem(order.Id,om.Id);
        List<Order> ordersInvoiced = new List<Order>{ order };
        Test.startTest();
        Grid_OrderServiceClass.updateFlrOrchestrationStatus(ordersInvoiced);
        Test.stopTest();
    }
    @IsTest
    static void nextScheduleNameTest() {
        Test.startTest();
        String output = Grid_OrderServiceClass.nextScheduleName('57.77');
        Assert.areEqual(output,'59');
        Test.stopTest();
    }

}