objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Signature_Date__c</fullName>
        <inlineHelpText>Date written next to the signature</inlineHelpText>
        <label>Contract Signature Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enddatee__c</fullName>
        <inlineHelpText>The date on which the supply of contracted goods or services end (ex. Last Delivery Contracted Date)</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>startDatee__c</fullName>
        <inlineHelpText>The date on which the supply of contracted goods or services begins (ex. First Delivery Contracted Date)</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity from which this contract was created</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__QuoteId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote from which this contract was created</description>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DeliveryPlan__c.object
<CustomObject>
    <fields>
        <fullName>Grid_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Delivery Plans</relationshipLabel>
        <relationshipName>Delivery_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Delivery Plans</relationshipLabel>
        <relationshipName>Delivery_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleCount__c</fullName>
        <inlineHelpText>Please put a number between 0 and 24</inlineHelpText>
        <label>Schedule Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleFrequency__c</fullName>
        <label>Schedule Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>One time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                    <isActive>false</isActive>
                    <label>Weekly</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grid_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Start_Month__c</fullName>
        <label>Start Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grid_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Grid_Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Plan</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Grid_DeliveryPlanControllerTest.cls
@isTest
public class Grid_DeliveryPlanControllerTest {
    @IsTest
    static void getDeliveryPlans() {
        System.runAs(TestDataFactory.createGridspertiseUser()) {
            Test.startTest();
            List<Deliveryplan__c> dlpList = new List<Deliveryplan__c>();
            Opportunity oppo = (Opportunity) TestDataFactory.createSObject(
                'Opportunity',
                new Map<String, Object>{ 'StageName' => 'Internal Review' },
                true
            );
            vlocity_cmt__PriceList__c spainPriceList = (vlocity_cmt__PriceList__c) TestDataFactory.createSObject(
                'vlocity_cmt__PriceList__c',
                new Map<String, Object>{
                    'CurrencyIsoCode' => 'EUR',
                        'vlocity_cmt__Code__c' => 'PL_ITALY_EUR'
                        },
                true
            );
            Id pricebookId = Test.getStandardPricebookId();
            Product2 p2 =  (Product2) TestDataFactory.createSObject(
                'Product2',
                new Map<String, Object>{ 'name' => 'y','Grid_Category__c' => 'Hardware' },
                true
            );
            Quote qte = (Quote) TestDataFactory.createSObject(
                'Quote',
                new Map<String, Object>{
                    'OpportunityId' => oppo.Id,
                        'Pricebook2Id' => pricebookId
                        },
                true
            );
            List<Quotelineitem> qlis = TestDataFactory.createQuoteLineItem(qte, 2);
            Contract c = (Contract) TestDataFactory.createSObject(
                'Contract',
                new Map<String, Object>{
                    'Status' => 'Draft',
                        'vlocity_cmt__OpportunityId__c' => oppo.Id,
                        'vlocity_cmt__QuoteId__c' => qte.Id,
                        'Contract_Signature_Date__c' => System.today(),
                        'startDatee__c' => System.today(),
                        'Enddatee__c' => System.today() + 6
                        },
                true
            );
            List<vlocity_cmt__ContractLineItem__c> clilist = new list <vlocity_cmt__ContractLineItem__c>();
             Map<String, Object> fieldsToUpdate= new Map<String, Object>{
                        //'Grid_Quote__c' => qte.Id,
                        'Grid_Contract__c' =>c.Id,
                        'Grid_StartDate__c' => System.today(),
                        'Grid_ScheduleCount__c' => 3,
                        'Grid_ScheduleFrequency__c' => 'Monthly',
                        'Grid_EndDate__c'=>System.today()+3,
                        'Grid_Version__c'=>1,
                        'Grid_Start_Month__c'=>'May'
                        };
            DeliveryPlan__c deliveryPlan = (DeliveryPlan__c) TestDataFactory.createSObject(
                'DeliveryPlan__c',
                new Map<String, Object>{
                        'Grid_Quote__c' => qte.Id,
                        'Grid_Contract__c' =>c.Id,
                        'Grid_StartDate__c' => System.today(),
                        'Grid_ScheduleCount__c' => 3,
                        'Grid_ScheduleFrequency__c' => 'Monthly',
                        'Grid_EndDate__c'=>System.today()+3,
                        'Grid_Version__c'=>1,
                        'Grid_Start_Month__c'=>'May'
                        },
                false
            );
            insert deliveryPlan;
           
            List<DeliveryPlan__c> deliveryPlanList = new List<DeliveryPlan__c>();
            deliveryPlanList.add(deliveryPlan);
            system.debug('list deliveryPlanList test class : '+deliveryPlanList);
            system.debug('list contractId test class : '+c.Id);

            Grid_DeliveryPlanController.getDeliveryPlans(deliveryPlan.Grid_Contract__c,1);
            Grid_DeliveryPlanController.updateDeliveryPlan(deliveryPlan.Id,fieldsToUpdate); 
            Test.stopTest();
        }
    }

}