objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Grid_Scheda231DeliveryStatus__c</fullName>
        <label>Scheda 231 Delivery Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open (red)</fullName>
                    <default>true</default>
                    <label>Open (red)</label>
                </value>
                <value>
                    <fullName>Closed(green)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheda_231_status__c</fullName>
        <label>Scheda 231 status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open (red)</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <label>Closed(green)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Grid_ContractBatchTest.cls
/**
 * Class to test the contract batch class 'Grid_ContractBatch'
 *
 * @Author  Salesforce
 *
 */
@IsTest
private class Grid_ContractBatchTest {
  @IsTest
  static void testContractBatch() {
    System.runAs(TestDataFactory.createGridspertiseUser()) {
      Test.startTest();
      List<Contract> contracts = (List<Contract>) TestDataFactory.createSObjectList(
        'Contract',
        new Map<String, Object>{ 'Scheda_231_status__c' => 'Open','Grid_Scheda231DeliveryStatus__c'=>'Open (red)' },
        50,
        true
      );
      Set<Id> contractsIds = new Set<Id>();
      for (Contract c : contracts) {
        contractsIds.add(c.Id);
      }
      Grid_ContractBatch b1 = new Grid_ContractBatch();
      Database.executeBatch(b1, 50);
      Test.stopTest();
      List<Task> tasks = [
        SELECT Id, WhatId
        FROM Task
        WHERE WhatId IN :contractsIds
      ];
      System.assert(tasks.size() > 0);
    }
  }
}