objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Signature_Date__c</fullName>
        <inlineHelpText>Date written next to the signature</inlineHelpText>
        <label>Contract Signature Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enddatee__c</fullName>
        <inlineHelpText>The date on which the supply of contracted goods or services end (ex. Last Delivery Contracted Date)</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>startDatee__c</fullName>
        <inlineHelpText>The date on which the supply of contracted goods or services begins (ex. First Delivery Contracted Date)</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity from which this contract was created</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__QuoteId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote from which this contract was created</description>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Grid_NonMandatoryChecklistTest.cls
/**
* Class to test the Non Mandatory Checklist Class
*
* @Author  Salesforce
*
*/
@isTest
private class Grid_NonMandatoryChecklistTest {
    
    
    @TestSetup
    private static void prepareData() {
        Id pricebookId = Test.getStandardPricebookId(); 
        Opportunity opp = (Opportunity) TestDataFactory.createSObject(
            'Opportunity',
            new Map<String, Object>{ 'StageName' => 'Negotiation' },
            true
        );
        Quote q = (Quote) TestDataFactory.createSObject(
            'Quote',
            new Map<String, Object>{
                'Status' => 'Approved',
                    'OpportunityId' => opp.Id
                    },
            true
        );
        Contract c = (Contract) TestDataFactory.createSObject(
            'Contract',
            new Map<String, Object>{
                'Status' => 'Draft',
                    'vlocity_cmt__OpportunityId__c' => opp.Id,
                    'vlocity_cmt__QuoteId__c' => q.Id,
                    'Contract_Signature_Date__c' => System.today(),
                    'startDatee__c' => System.today(),
                    'Enddatee__c' => System.today() + 5
                    },
            true
        );
        
    }
     
    @isTest
    private static void updateChecklistTest() {
        Test.startTest();
        Contract contractTpUpdate = [Select Id From Contract];
        List<String> selectedItems = new List<String>{'profitLoss','signedContract','variousOffers','technicalOffer'};
        Grid_NonMandatoryChecklist.updateChecklist(contractTpUpdate.id, selectedItems);
        Test.stopTest();
    }
}