objects/DeliveryPlan__c.object
<CustomObject>
    <fields>
        <fullName>Grid_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Delivery Plans</relationshipLabel>
        <relationshipName>Delivery_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Delivery Plans</relationshipLabel>
        <relationshipName>Delivery_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleCount__c</fullName>
        <inlineHelpText>Please put a number between 0 and 24</inlineHelpText>
        <label>Schedule Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleFrequency__c</fullName>
        <label>Schedule Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>One time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                    <isActive>false</isActive>
                    <label>Weekly</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grid_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Grid_Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Plan</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DeliveryPlanTriggerHandler.cls
/**
 * Class to implement the trigger handler for Opportunity Object
 *
 * @Author  Salesforce
 *
 */
public class DeliveryPlanTriggerHandler extends TriggerHandler {

  Map<Id, DeliveryPlan__c> deliveryNewMap = new Map<Id, DeliveryPlan__c>();
  Map<Id, DeliveryPlan__c> deliveryOldMap = new Map<Id, DeliveryPlan__c>();
  List<DeliveryPlan__c> deliveryPlanList = new List<DeliveryPlan__c>();
  Set<Id> quoteIds = new Set<Id>();
  Set<Id> contractIds = new Set<Id>();

  public DeliveryPlanTriggerHandler() {
    deliveryNewMap = (Map<Id, DeliveryPlan__c>) Trigger.newMap;
    deliveryOldMap = (Map<Id, DeliveryPlan__c>) Trigger.oldMap;
    for (DeliveryPlan__c dlp : deliveryNewMap.values()) {
      if(dlp.Grid_Version__c == 1){
        quoteIds.add(dlp.Grid_Quote__c);
      }
      if(dlp.Grid_Version__c == 2){
        contractIds.add(dlp.Grid_Contract__c);
      }
    } 
  }

  public override void afterInsert() {
    if(!quoteIds.isEmpty()){
      Grid_QuoteServiceClass.createProductSchedule(deliveryNewMap.values(), quoteIds);
    }
    if(!contractIds.isEmpty()){
      Grid_WithoutSharingServiceClass.createProductSchedule(deliveryNewMap.values(), contractIds);
    } 
   }

  public override void afterUpdate() {
    for (Id newDlId : deliveryNewMap.keySet()) {
      if (
        deliveryNewMap.get(newDlId).Grid_ScheduleFrequency__c !=
        deliveryOldMap.get(newDlId).Grid_ScheduleFrequency__c ||
        deliveryNewMap.get(newDlId).Grid_ScheduleCount__c !=
        deliveryOldMap.get(newDlId).Grid_ScheduleCount__c ||
        deliveryNewMap.get(newDlId).Grid_StartDate__c !=
        deliveryOldMap.get(newDlId).Grid_StartDate__c
      ) {
        deliveryPlanList.add(deliveryNewMap.get(newDlId));
      }   
    }
    if (!deliveryPlanList.isEmpty()) {
      if(!quoteIds.isEmpty()){
        Grid_QuoteServiceClass.deleteProductSchedule(deliveryPlanList);
        Grid_QuoteServiceClass.createProductSchedule(deliveryPlanList, quoteIds);
      }
      if(!contractIds.isEmpty()){
        Grid_WithoutSharingServiceClass.deleteProductSchedule(deliveryPlanList);
        Grid_WithoutSharingServiceClass.createProductSchedule(deliveryPlanList, contractIds);
      }
    }
  }
}