objects/DeliveryPlan__c.object
<CustomObject>
    <fields>
        <fullName>Grid_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Delivery Plans</relationshipLabel>
        <relationshipName>Delivery_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_IsCloned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is cloned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleCount__c</fullName>
        <inlineHelpText>Please put a number between 0 and 24</inlineHelpText>
        <label>Schedule Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleFrequency__c</fullName>
        <label>Schedule Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>One time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                    <isActive>false</isActive>
                    <label>Weekly</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grid_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Start_Month__c</fullName>
        <label>Start Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grid_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Grid_Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Plan</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Grid_DeliveryPlanController.cls
/**
 * Class to implement the Delivery Plan Controller
 *
 * @Author  Salesforce
 *
 */
public without sharing class Grid_DeliveryPlanController {
    /**
     * @description get list of delivery plans
     * @param String cId contract id
     * @return List<DeliveryPlan__c>
     **/
    @AuraEnabled(cacheable=true)
    public static List<DeliveryPlan__c> getDeliveryPlans(String cId, Integer Cversion) {
      List<DeliveryPlan__c> deliveryPlans = [
          SELECT Grid_ScheduleFrequency__c, Grid_ScheduleCount__c, Grid_StartDate__c, Grid_EndDate__c
          FROM DeliveryPlan__c 
          WHERE Grid_Contract__r.Id = :cId AND Grid_Version__c = :Cversion
      ];
      return deliveryPlans;
  }

    /**
     * @description update delivery plans with new fields
     * @param String deliveryPlanId, Map<String, Object> fieldsToUpdate
     * @return void
     **/
    @AuraEnabled
    public static void updateDeliveryPlan(String deliveryPlanId,Map<String, Object> fieldsToUpdate) {
        List<DeliveryPlan__c> deliveryPlans = [
            SELECT Grid_ScheduleFrequency__c, Grid_ScheduleCount__c, Grid_StartDate__c, Grid_EndDate__c, Grid_Start_Month__c,Grid_IsCloned__c
            FROM DeliveryPlan__c 
            WHERE Id = :deliveryPlanId Limit 1
        ];
        if (deliveryPlans[0] != null) {
            for (String fieldName : fieldsToUpdate.keySet()) {
                Object fieldValue = fieldsToUpdate.get(fieldName);
                if (fieldValue instanceof String && Schema.getGlobalDescribe().get('DeliveryPlan__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getType() == Schema.DisplayType.Date) {
                    Date convertedDate = Date.valueOf((String)fieldValue);
                    deliveryPlans[0].put(fieldName, convertedDate);
                } else if(fieldValue instanceof String && Schema.getGlobalDescribe().get('DeliveryPlan__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getType() == Schema.DisplayType.Double) {
                    deliveryPlans[0].put(fieldName, Decimal.valueOf((String)fieldValue));
                } else {
                    deliveryPlans[0].put(fieldName, fieldValue);
                }     
            }

        update deliveryPlans;

        }
    }
  
  }