objects/DeliveryPlan__c.object
<CustomObject>
    <fields>
        <fullName>Grid_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Delivery Plans</relationshipLabel>
        <relationshipName>Delivery_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleCount__c</fullName>
        <inlineHelpText>Please put a number between 0 and 24</inlineHelpText>
        <label>Schedule Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_ScheduleFrequency__c</fullName>
        <label>Schedule Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>One time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                    <isActive>false</isActive>
                    <label>Weekly</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grid_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Grid_Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Plan</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductSchedule__c.object
<CustomObject>
    <fields>
        <fullName>Grid_Actual_Amount__c</fullName>
        <formula>Grid_SalesPric__c  *  Grid_Actual_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_Actual_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_ContractLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Line</label>
        <referenceTo>vlocity_cmt__ContractLineItem__c</referenceTo>
        <relationshipLabel>Product Schedules</relationshipLabel>
        <relationshipName>Product_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_Delivery_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Plan</label>
        <referenceTo>DeliveryPlan__c</referenceTo>
        <relationshipLabel>Product Schedules</relationshipLabel>
        <relationshipName>Product_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_OrderSort__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Grid_OrderSort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_PlannedAmn__c</fullName>
        <formula>Grid_PlannedQuantity__c  *   Grid_SalesPric__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Planned Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_PlannedQuantity__c</fullName>
        <label>Planned Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grid_QuoteLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Product Schedules</relationshipLabel>
        <relationshipName>Product_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grid_SalesPric__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grid_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grid_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Grid_Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Grid_ProductScheduelleController.cls
/**
 * Class to implement the Product Schedules Controller
 *
 * @Author  Salesforce
 *
 */
public with sharing class Grid_ProductScheduelleController {
  /**
   * @description get list of delivery plan terms
   * @param String qId quote id
   * @return List<Grid_DeliveryPlanTerm>
   **/
  @AuraEnabled(cacheable=true)
  public static List<Grid_DeliveryPlanTerm> getProductSchedules(String qId) {
    List<String> activatedStatus = new List<String>{'Activated', 'Closed/under warranty'};
    Map<String, List<ProductSchedule__c>> productSchedulesMap = new Map<String, List<ProductSchedule__c>>();
    List<Grid_DeliveryPlanTerm> deliPlanTerms = new List<Grid_DeliveryPlanTerm>();
    Set<String> periodsSet = new Set<String>();
    String totalQuantity = '';
    Integer versionNumber = 1;
    String cStatus = '';
    String profileName = [SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId()].Name;
    String kamProfile = Label.KAM_profile;

    if(qId.startsWithIgnoreCase('800')){
      Contract contract = [SELECT Id, Status FROM Contract WHERE Id = :qId];
      cStatus = contract.Status;
      if (!profileName.equals(kamProfile) && activatedStatus.contains(cStatus)) {
        versionNumber = 2;
      }
    }
    List<ProductSchedule__c> productScheduleList =  [
      SELECT
        ID,
        Name,
        Grid_PlannedQuantity__c,
        Grid_SalesPric__c,
        Grid_PlannedAmn__c,
        Grid_StartDate__c,
        Grid_QuoteLineItem__r.Product2.Name,
        Grid_EndDate__c,
        Grid_OrderSort__c,
        Grid_QuoteLineItem__r.Quantity,
        Grid_QuoteLineItem__r.LineNumber,
        Grid_QuoteLineItem__c,
        Grid_Actual_Quantity__c,
        Grid_Actual_Amount__c,
        Grid_Version__c,
        Grid_ContractLine__r.vlocity_cmt__ContractId__c,
        Grid_Delivery_Plan__c
      FROM ProductSchedule__c
      WHERE
        (Grid_QuoteLineItem__r.Quote.Id = :qId 
        OR Grid_ContractLine__r.vlocity_cmt__ContractId__c = :qId)
        AND (Grid_Version__c = :versionNumber)
      ORDER BY Grid_StartDate__c ASC
    ];
      System.debug(qId);
    for (ProductSchedule__c ps : productScheduleList) {
      if (!productSchedulesMap.containsKey(ps.Grid_QuoteLineItem__r.Product2.Name + '_' + ps.Grid_QuoteLineItem__r.LineNumber)) {
        productSchedulesMap.put(ps.Grid_QuoteLineItem__r.Product2.Name + '_' + ps.Grid_QuoteLineItem__r.LineNumber, new List<ProductSchedule__c>());
      }
      periodsSet.add(ps.Name);
      System.debug(ps.Grid_Delivery_Plan__c);
      productSchedulesMap.get(ps.Grid_QuoteLineItem__r.Product2.Name + '_' + ps.Grid_QuoteLineItem__r.LineNumber).add(ps);
    }
    for (String productSchedule : productSchedulesMap.KeySet()) {
      totalQuantity ='' + Integer.ValueOf(productSchedulesMap.get(productSchedule)[0].Grid_QuoteLineItem__r.Quantity);
      Grid_DeliveryPlanTerm dp = new Grid_DeliveryPlanTerm();
      dp.productNameId = productSchedule;
      dp.productName = productSchedulesMap.get(productSchedule)[0].Grid_QuoteLineItem__r.Product2.Name;
      dp.metric = '';
      dp.total = totalQuantity;
      dp.periods = new List<String>(periodsSet);
      dp.productSchedules = productSchedulesMap.get(productSchedule);
      dp.contractStatus = cStatus;
      dp.dpVersion = versionNumber;
      deliPlanTerms.add(dp);

    }

    return deliPlanTerms;
  }
  /**
   * @description refresh delivery plan
   * @param String qId quote id
   * @return void
   **/
  @AuraEnabled
  public static void refreshDeliveryPlan(String qId) {
    List<DeliveryPlan__c> deliveryPlan = [
      SELECT
        Id,
        Grid_Quote__c,
        Grid_StartDate__c,
        Grid_ScheduleCount__c,
        Grid_ScheduleFrequency__c
      FROM DeliveryPlan__c
      WHERE Grid_Quote__c = :qId
      AND (Grid_Version__c = 1)
    ];
    Set<Id> quoteIds = new Set<Id>();
    quoteIds.add(qId);
    Grid_QuoteServiceClass.deleteProductSchedule(deliveryPlan);
    Grid_QuoteServiceClass.createProductSchedule(deliveryPlan, quoteIds);
  }

}